Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,10 +1,10 @@
-name: Create Branch, Replace Strings, and Push Changes
+name: Common Component Maker
 
 on:
   workflow_dispatch:
     inputs:
       branchName:
-        description: 'Name of the new branch'
+        description: 'Name of the new branch. It should start with "feature" and not be "main".'
         required: true
       oldString:
         description: 'Old string to replace'
@@ -17,6 +17,16 @@ jobs:
   create_and_replace:
     runs-on: ubuntu-latest
     steps:
+      - name: Check branch name format
+        run: |
+          if [[ "${{ github.event.inputs.branchName }}" == "main" ]]; then
+            echo "Branch name cannot be 'main', please provide a different name."
+            exit 1
+          elif [[ ! "${{ github.event.inputs.branchName }}" =~ ^feature.* ]]; then
+            echo "Branch name should start with 'feature', please provide a different name."
+            exit 1
+          fi
+
       - name: Checkout main branch
         uses: actions/checkout@v2
         with:
